name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Prettier
        run: npm prettify
      - name: Tests
        run: |
          npm run test:cli
          npm run test
      - name: Build
        run: npm run build
